Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: /root/fabric-ws/simple-demo/crypto-config/ordererOrganizations/simple-network.com/msp

    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: /root/fabric-ws/simple-demo/crypto-config/peerOrganizations/org1.simple-network.com/msp
        AnchorPeers:
                - Host: peer0.org1.simple-network.com
                - Port: 7051
    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: /root/fabric-ws/simple-demo/crypto-config/peerOrganizations/org2.simple-network.com/msp
        AnchorPeers:
                - Host: peer0.org2.simple-network.com
                - Port: 7051
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.simple-network.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
Application: &ApplicationDefaults
    Organizations:

Profiles: 
    TestTwoOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                    - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                        - *Org1
                        - *Org2
    TestTwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
                <<: *ApplicationDefaults
                Organizations:
                        - *Org1
                        - *Org2
