OrdererOrgs:
  - Name: Orderer
    Domain: hwsj.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.hwsj.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.hwsj.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
